version: '3.7'
services:
  vk-backend:
    image: jagmesh/vk-backend:latest
    container_name: vk-container
    ports:
      - "80:1337"  
    restart: always
  gifnot:
    image: garageorder/vkgifnot:latest
    container_name: gifnot-container
    environment:
      - GIF_TOKEN=SAMPLE_TEXT
      - NOTIFIER_TOKEN=ENTER_TEXT
      - NOTIFIED_USERS=185241998 30152694 197154078
    restart: always